vat_lieu_xay_dung/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
// use App\Http\Controllers\accountcontroller;
use App\Http\Middleware\admin;
use App\Http\Controllers\admincontroller;
use App\Http\Controllers\categoriescontrller;
use App\Http\Controllers\itemcontroller;
use App\Models\item;
use App\Models\category;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// user
Route::resource('item','itemcontroller')->only(['index', 'show']);
Route::resource('categories','categoriescontrller')->only(['show']); 
Route::post('finditem','itemcontroller@find')->name('finditem');

// admin
Route::get('loginadmin','admincontroller@formLogin')->name('login.form');
Route::post('login','admincontroller@login')->name('login.admin');

Route::group(['middleware' => 'admin'], function() {
    Route::resource('item','itemcontroller')->only(['store', 'edit', 'update', 'destroy']); 

    Route::get('create','itemcontroller@create')->name('item.create');

    Route::get('update','itemcontroller@edit_delete')->name('item.update');
    Route::get('find_update','itemcontroller@find_update')->name('find.admin');
    Route::get('form_delete/{id}','itemcontroller@form_delete')->name('form.delete');
    Route::post('logout','admincontroller@logout')->name('admin.logout'); 
});

vat_lieu_xay_dung/app/Models/item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use App\Models\category;

class item extends Model
{
    use HasFactory;
    protected $table = 'item';
    public $timestamps = false ;
    protected $perPage = 5;
    protected $fillable = ['name','description', 'amount', 'price','image', 'categories_id'];

    public function allItems()
    {
        return DB::table('item')->paginate(15);
    }
    public function createItem($request)
    {
        $input = $request->validated();
        $input['image'] = $input['image']->getClientOriginalName();
        $image = $request->file('image');
        $image->move('image', $input['image']);
        $add = item::create($input);
        return session()->flash('message','create item successfully');
    }
    public function item()
    {
        return $this->BelongsTo('App\Models\category', 'categories_id', 'id');
    }

    public function showItem($id)
    {
        $item = item::find($id);
        return $item;
    } 

    public function findItem($request)
    {   
        $name = $request->validated();
        $items = item::query()
                ->where('name', 'LIKE', "%{$name['name']}%") 
                ->orWhere('description', 'LIKE', "%{$name['name']}%") 
                ->get();
        return $items;
    }

    public function delete_item($id)
    {   
        $item = item::find($id);
        $item->delete();
    }

    public function update_item($request, $id)
    {
        $input = $request->validated();
        $item = item::find($id);
        $item->name = $input['name'];
        $item->description = $input['description'];
        $item->price = $input['price'];
        $item->save();
    } 

    public function support($id)
    {
        $categories = item::find($id)->categories_id;
        $support = DB::table('item')
                    ->where('categories_id', '=', $categories)
                    ->get();
        $random =  $support->random(10)->all();

        return $random;
        
    }
    
}

vat_lieu_xay_dung/app/Http/Controllers/itemcontroller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\item;
use App\Models\Admin;
use App\Models\category;
use App\Http\Requests\itemcreaterequest;
use App\Http\Requests\find_itemrequest;
use App\Http\Requests\item_updaterequest;

class itemcontroller extends Controller
{
    public $item;
    public $admin;
    public function __construct(item $item, Admin $admin)
    {
        $this->item = $item;
        $this->admin = $admin;
    } 
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $data = $this->item->allItems();
        return view('item.all',['data' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('item.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(itemcreaterequest $request)
    {
        $items = $this->item->createItem($request);
        session()->flash('message','tạo sản phẩm thành công');
        return redirect()->route('item.create');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = $this->item->showItem($id);
        $support = $this->item->support($id);
        return view('item.show',['item' => $item, 'support' => $support]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = $this->item->showItem($id);
        return view('item.show_update',['item' => $item]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(item_updaterequest $request, $id)
    {
        $item = $this->item->update_item($request, $id);
        session()->flash('message','cập nhật thàng công');
        return redirect()->route('item.update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->item->delete_item($id);
        session()->flash('message','đã xóa thành công');
        return redirect()->route('item.update');
    }

    //build

    /**
     * product search by id
     *
     * @param find_itemrequest
     * @return \Illuminate\Http\Response
     */
    public function find(find_itemrequest $request)
    {   
        $item = $this->item->findItem($request);
        return view('item.find',['data' => $item]);
    }

    /**
     * load form item delete
     *
     * @return \Illuminate\Http\Response
     */
    public function edit_delete()
    {   
        $data = $this->item->allItems();
        return view('item.update_delete',['data' => $data]);
    }

    /**
     * product search by name
     *
     * @param find_itemrequest
     * @return \Illuminate\Http\Response
     */
    public function find_update(find_itemrequest $request)
    {   
        $item = $this->item->findItem($request);
        return view('item.find_update',['data' => $item]);
    }

    /**
     * product delete by id
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function form_delete($id)
    {   
        $item = $this->item->showItem($id);
        return view('item.delete',['item' => $item]);
    }
}

vat_lieu_xay_dung/resources/views/item/all.blade.php
@extends('home')
@section('title', 'all items')
@section('content')
    <div class="wrapper">
        @foreach($data as $dt)
            <div class="conten_child">
                <a href="http://localhost:8000/item/{{$dt->id}}"> <img src="/image/{{$dt->image}}"  height="250px" width="250px" /></a>
                <h4 style="color:red"><strike> ({{$dt->price+($dt->price)*0.2}})VND</strike><h4>
                <h3>giá:{{$dt->price}} VND<h3>
                <a href="http://localhost:8000/item/{{$dt->id}}"><h3><b>{{$dt->name}}</b></h3></a>
            </div>
        @endforeach
        <div class="next">
            <spam>
                {{ $data->links() }}
            </spam>
        </div>
    </div>
@endsection 

vat_lieu_xay_dung/resources/views/item/categories.blade.php
@extends('home')
@section('title', 'categories items')
@section('content')
    <div>
        <h1>{{$categories->name}}</h1>
    </div>
    <div class="wrapper">
        @foreach($categories->item as $item)
            <div class="conten_child">
                <a href="http://localhost:8000/item/{{$item->id}}"> <img src="/image/{{$item->image}}"  height="300px" width="300px" /></a>
                <h4 style="color:red"><strike> ({{$item->price+($item->price)*0.2}})VND</strike><h4>
                <h3> giá:{{$item->price}} vnd<h3>
                <a href="http://localhost:8000/item/{{$item->id}}"><b><h3>{{$item->name}}</h3></b></a>
            </div>
        @endforeach
    </div>
@endsection 

vat_lieu_xay_dung/resources/views/item/create.blade.php
@extends('admin.admin_home')
@section('title', 'create item')
@section('content')
  <div class="conten">
        @if(session()->has('message'))
            <div style='color:blue'>{{session('message')}}</div>
        @endif
        <a href="http://localhost:8000/update"><b><h2>TRANG CHỦ</h2></b></a>
        <form action ="{{route('item.store')}}"  class = 'text-center'  enctype="multipart/form-data" method ='POST'>
            @csrf
            <div >
                <h3>TẠO SẢN PHẨM</h3>
            </div>
            <div  class="control">
                <lable for = 'name' >TÊN SẢN PHẨM</lable><br/>
                <input type = textbox name = 'name' id = 'name' size="50">
            </div>
            <div  class="control">
                <lable for = 'description'>MIÊU TẢ</lable><br/>
                <textarea rows="4" cols="50" name="description" > </textarea>
            </div>
            <div class="control">
                <lable for='price'>GIÁ BÁN</lable><br/>
                <input type = 'textbox'  name = 'price' id='price' size="50">
            </div> 
            <div  class="control">
                <div class="image_input">
                    <lable for='price'>HÌNH ẢNH</lable><br/>
                    <input type="file" name="image" id = 'image' class ="image_input"> 
                </div>
            </div> 
            <div class="control">
                <input type="radio" id="contactChoice1"
                    name="categories_id" value="1" checked>
                <label for="contactChoice1">GẠCH LỖ</label>
                <input type="radio" id="contactChoice2"
                    name="categories_id" value="2">
                <label for="contactChoice2">XI MĂNG</label>
                <input type="radio" id="contactChoice3"
                    name="categories_id" value="3">
                <label for="contactChoice3">THÉP</label>
                <input type="radio" id="contactChoice3"
                    name="categories_id" value="4">
                <label for="contactChoice3">GẠCH TRANG TRÍ</label>
                <input type="radio" id="contactChoice3"
                    name="categories_id" value="5">
                <label for="contactChoice3">THIẾT BỊ VỆ SINH</label>
            </div>
            <div class="control">
                <button type = 'submit' name = 'submit' class = 'btn btn-primary'>TẠO SẢN PHẨM</button> 
            </div>
        </form> 
  </div>
@endsection

vat_lieu_xay_dung/resources/views/item/delete.blade.php
@extends('admin.admin_home')
@section('title', 'edit item')
@section('content')
    <div class="update"> 
    @csrf
        <div class="update1">
            <h1>THÔNG TIN SẢN PHẨM</h1>
            <a href="http://localhost:8000/update"><b><h2>TRANG CHỦ</h2></b></a>
        </div>
        <div class="update2">   
            <div class="update3">
                <table>
                    <thead>
                        <tr>
                            <th class="headertable1">TÊN MẶT HÀNG</th>
                            <th class="headertable2">ĐẶC ĐIỂM </th>
                            <th class="headertable3">GIÁ</th>
                            <th class="headertable1">CHỦNG LOẠI</th>
                            <th class="headertable1">HÌNH ẢNH</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="headertable1">{{$item->name}}</div></td>
                            <td class="tbody1">{{$item->description}}</div></td>
                            <td class="headertable3">{{$item->price}}</div></td>
                            <td class="headertable1">{{$item->item->name}}</div></td>
                            <td class="headertable1"><img src="/image/{{$item->image}}" height="100px" width="100px"/></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="form_delete">
                <div class="form_delete2">
                    <form method="POST" action="http://localhost:8000/item/{{$item->id}}">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <button type = 'submit' name='submit' class = 'btn btn-primary'>XÓA</button>
                    </form>  
                </div>
                <div class="form_delete2">
                    <form action="{{route('item.update')}}">
                    @csrf
                        <button type = 'submit' name='submit' class = 'btn btn-primary'>THOÁT</button>
                    </form>    
                </div>
            </div>
        </div>
    </div>
@endsection

vat_lieu_xay_dung/resources/views/item/find.blade.php
@extends('home')
@section('title', 'find items')
@section('content')
    <div class="wrapper">
        @foreach($data as $dt)
            <div class="conten_child">
                <a href="http://localhost:8000/item/{{$dt->id}}"> <img src="/image/{{$dt->image}}"  height="300px" width="300px" /></a>
                <h5> giá:{{$dt->price}} vnd<h5>
                <a href="http://localhost:8000/item/{{$dt->id}}"><b>{{$dt->name}}</b></a>
            </div>
        @endforeach
    </div>
@endsection 

vat_lieu_xay_dung/resources/views/item/find_update.blade.php
@extends('admin.admin_home')
@section('title', 'all items')
@section('content')
    <div id ="content"> 
    @csrf
        <div class="update1">
            <h1>TÌM KIẾM SẢN PHẨM</h1>
            <a href="http://localhost:8000/update"><b><h3>TRANG CHỦ</h3></b></a>
        </div>  
        <div id="table" > 
            <table>
                <thead>
                    <tr>
                        <th id = "headertable">STT</th>
                        <th id = "headertable">TÊN MẶT HÀNG</th>
                        <th id = "headertable">ĐẶC ĐIỂM </th>
                        <th id = "headertable">GIÁ</th>
                        <th id = "headertable">HÌNH ẢNH</th>
                        <th id = "headertable"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($data as $key => $item)
                        <tr id ="data">
                            <td>{{$key + 1}}</td>
                            <td>{{$item->name}}</td>
                            <td>{{$item->description}}</td>
                            <td>{{$item->price}}</td>
                            <td><img src="image/{{$item->image}}"  height="100px" width="100px" /></td>
                            <td>
                                <div padding: 10px>
                                    <form action="{{route('form.delete', $item->id)}}">
                                    @csrf
                                        <button type = 'submit' name='submit' class = 'btn btn-primary'>XÓA</button> 
                                    </form>
                                    <form action ="{{route('item.edit', $item->id)}}">
                                    @csrf
                                        <button type = 'submit' name='submit' class = 'btn btn-primary' >SỬA</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection 

vat_lieu_xay_dung/resources/views/item/show.blade.php
@extends('home')
@section('title', 'show item')
@section('content')
    <div class="show_wrapper">
        <div> 
            <img src="/image/{{$item->image}}" height="400" width="400" />
        </div>
        <div class="show_grandchildren">
            <div><h4>TÊN SẢN PHẨM : {{$item->name}}<h4></div>
            <div><h4>CHỦNG LOẠI : {{$item->item->name}}<h4></div>
            <div><h4>GIÁ SẢN PHẨM : {{$item->price}} VND<h4></div>
            <div><h4>LIỆN HỆ SỐ ĐIỆN THOẠI : 0123456789 <h4></div>
            <div> 
                <img src="/image/{{$item->image}}" height="200" width="200"/>
            </div>
            <div><h4>ĐẶC ĐIỂM SẢN PHẨM : {{$item->description}}<h4></div>
        </div>
        <div>
        </div>
        <div class="show_child">
            <div class="tu_van">
                <img src="/image/tu-van-san-pham.png" height="75" width="75" />
                <div>
                    <h4>TƯ VẤN 24/24</h4>
                    <h4>Hotline: 0978 956 655</h4>  
                </div>
            </div>
            <div class="tu_van">
                <img src="/image/giao-nhan.png" height="75" width="75" />
                <div>
                    <h4>Giao hàng toàn quốc</h4>
                    <h4>Vận chuyển 63 tỉnh thành</h4> 
                </div>
            </div>
            <div class="tu_van">
                <img src="/image/icon-uy-tin-7933-5903.png" height="75" width="75" />
                <div>
                    <h4>BẢO HÀNH TẬN NƠI</h4>
                    <h4>Nhanh chóng và đảm bảo</h4> 
                </div>
            </div>
            <div class="tu_van">
                <img src="/image/ho-tro-thi-cong.png" height="75" width="75" />
                <div>
                    <h4>Tư vấn thiết kế</h4>
                    <h4>Tư vấn bản vẽ thiết kế</h4> 
                </div>
            </div>
            <div class="tu_van">
                <img src="/image/gia-hang.png" height="150" width="250" />
            </div>  
        </div>
    </div>
    ***********************************************************************************
    <div>
        <h3> SẢN PHẨM BẠN CÓ THỂ QUAN TÂM </h3>
    </div>
    <div>
    <div class="wrapper_copy">
        @foreach($support as $dt)
            <div class="conten_child">
                <a href="http://localhost:8000/item/{{$dt->id}}"> <img src="/image/{{$dt->image}}"  height="250px" width="250px" /></a>
                <h4 style="color:red"><strike> ({{$dt->price+($dt->price)*0.2}})VND</strike><h4>
                <h4>giá:{{$dt->price}} VND<h4>
                <a href="http://localhost:8000/item/{{$dt->id}}"><h4><b>{{$dt->name}}</b></h4></a>
            </div>
        @endforeach
    </div>
    </div>

@endsection 

vat_lieu_xay_dung/resources/views/item/show_update.blade.php
@extends('admin.admin_home')
@section('title', 'edit item')
@section('content')
    <div class="update" > 
    @csrf
        <div class="update1">
            <h1>THÔNG TIN SẢN PHẨM</h1>
            <a href="http://localhost:8000/update"><b><h2>TRANG CHỦ</h2></b></a>
        </div>
        <div class="update2">
            <form method="POST" action="http://localhost:8000/item/{{$item->id}}">
            {{ csrf_field() }}
            {{ method_field('PATCH') }}
                <div class="update3">
                    <table>
                        <thead>
                            <tr>
                                <th class="headertable1">TÊN MẶT HÀNG</th>
                                <th class="headertable2">ĐẶC ĐIỂM </th>
                                <th class="headertable3">GIÁ</th>
                                <th class="headertable1">CHỦNG LOẠI</th>
                                <th class="headertable1">HÌNH ẢNH</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="headertable1">{{$item->name}}</div></td>
                                <td class="tbody1">{{$item->description}}</div></td>
                                <td class="headertable3">{{$item->price}}</div></td>
                                <td class="headertable1">{{$item->item->name}}</div></td>
                                <td class="headertable1"><img src="/image/{{$item->image}}" height="100px" width="100px"/></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div>
                    <div  class="control">
                        <lable for = 'name' >NHẬP TÊM MỚI SẢN PHẨM</lable><br/>
                        <input type = textbox name = 'name' id = 'name' size="50" value = "{{$item->name}}">
                    </div>
                    <div  class="control">
                        <lable for = 'description'>MIÊU TẢ</lable><br/>
                        <textarea rows="4" cols="50" name="description">{{$item->description}}</textarea>
                    </div>
                    <div class="control">
                        <lable for='price'>GIÁ MỚI</lable><br/>
                        <input type = 'textbox'  name = 'price' id='price' size="50"  value = "{{$item->price}}">
                    </div> 
                </div>
                <div>
                    <button type = 'submit' name='submit' class = 'btn btn-primary'>CẬP NHẬT</button>
                </div>
            </form>
        </div>
    </div>
@endsection

vat_lieu_xay_dung/resources/views/item/update_delete.blade.php
@extends('admin.admin_home')
@section('title', 'all items')
@section('content')
    <div > 
        <div class="sesion">
            <div>
                <h1>TẤT CẢ SẢN PHẨM</h1>
            </div>
            @if(session()->has('message'))
                <div style='color:blue'>{{session('message')}}</div>
            @endif
            <div class="show" >
                <div class="show1" >
                    <form action ="{{ route('item.create')}}">
                    @csrf
                        <button type = 'submit' name='submit' class = 'btn btn-primary'>THÊM SẢN PHẨM</button> 
                    </form>
                </div>
            </div>
                <form action ="{{ route('find.admin')}}" placeholder="Search" method ='get' class = 'text-center'>
                    @csrf
                    <div >
                        <div >
                            <input type = 'text' name = 'name'>
                        </div>
                        <div >
                            <button type = 'submit' name = 'submit' class = 'btn btn-primary'>TÌM KIẾM</button> 
                        </div>
                    </div>
                </form>   
            </div>
        </div>
        <div> 
            <table>
                <thead>
                    <tr>
                        <th id = "headertable">STT</th>
                        <th id = "headertable">TÊN MẶT HÀNG</th>
                        <th id = "headertable">ĐẶC ĐIỂM </th>
                        <th id = "headertable">GIÁ</th>
                        <th id = "headertable">HÌNH ẢNH</th>
                        <th id = "headertable"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($data as $key => $item)
                        <tr id ="data">
                            <td>{{$key + 1}}</td>
                            <td>{{$item->name}}</td>
                            <td>{{$item->description}}</td>
                            <td>{{$item->price}}</td>
                            <td><img src="/image/{{$item->image}}"  height="100px" width="100px" /></td>
                            <td>
                                <div padding: 10px>
                                    <form action="{{route('form.delete', $item->id)}}">
                                    @csrf
                                        <button type = 'submit' name='submit' class = 'btn btn-primary'>XÓA</button> 
                                    </form>
                                    <form action="{{route('item.edit', $item->id)}}">
                                    @csrf
                                        <button type = 'submit' name='submit' class = 'btn btn-primary' >SỬA</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div >
            <spam>
                {{ $data->links() }}
            </spam>
        </div>
    </div>
@endsection 